language: "pt-BR"

reviews:
  auto_review:
    enabled: true
    drafts: false
    request_changes_workflow: true
    base_branches:
      - main
      - develop
  finishing_touches:
    docstrings:
      enabled: false

chat:
  auto_reply: true
