run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gofumpt
    - gosec
    - govulncheck
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  gofumpt:
    extra-rules: true
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
