run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
