// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    id,
    actor_id,
    actor_name,
    action,
    resource_type,
    resource_id,
    changes,
    ip_address,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, actor_id, actor_name, action, resource_type, resource_id, changes, ip_address, created_at
`

type CreateAuditLogParams struct {
	ID           uuid.UUID          `json:"id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorName    string             `json:"actor_name"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Changes      []byte             `json:"changes"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Changes,
		arg.IpAddress,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Changes,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
