// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: configuration.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemState = `-- name: CreateSystemState :one
INSERT INTO system_state (id, onboarding_completed, onboarding_completed_at, system_instance_id, telemetry_enabled, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, onboarding_completed, onboarding_completed_at, system_instance_id, telemetry_enabled, metadata, created_at, updated_at
`

type CreateSystemStateParams struct {
	ID                    uuid.UUID          `json:"id"`
	OnboardingCompleted   bool               `json:"onboarding_completed"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	SystemInstanceID      uuid.UUID          `json:"system_instance_id"`
	TelemetryEnabled      bool               `json:"telemetry_enabled"`
	Metadata              []byte             `json:"metadata"`
}

func (q *Queries) CreateSystemState(ctx context.Context, arg CreateSystemStateParams) (SystemState, error) {
	row := q.db.QueryRow(ctx, createSystemState,
		arg.ID,
		arg.OnboardingCompleted,
		arg.OnboardingCompletedAt,
		arg.SystemInstanceID,
		arg.TelemetryEnabled,
		arg.Metadata,
	)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.OnboardingCompleted,
		&i.OnboardingCompletedAt,
		&i.SystemInstanceID,
		&i.TelemetryEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemState = `-- name: GetSystemState :one
SELECT id, onboarding_completed, onboarding_completed_at, system_instance_id, telemetry_enabled, metadata, created_at, updated_at FROM system_state LIMIT 1
`

func (q *Queries) GetSystemState(ctx context.Context) (SystemState, error) {
	row := q.db.QueryRow(ctx, getSystemState)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.OnboardingCompleted,
		&i.OnboardingCompletedAt,
		&i.SystemInstanceID,
		&i.TelemetryEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemStateOnboarding = `-- name: UpdateSystemStateOnboarding :exec
UPDATE system_state
SET onboarding_completed = true, onboarding_completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSystemStateOnboarding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSystemStateOnboarding, id)
	return err
}
