// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCredentials = `-- name: CountCredentials :one
SELECT COUNT(*) FROM credentials
`

func (q *Queries) CountCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id,
    name,
    type,
    encrypted_data,
    description,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, type, encrypted_data, description, created_at, updated_at
`

type CreateCredentialParams struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	EncryptedData string             `json:"encrypted_data"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.EncryptedData,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EncryptedData,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :execrows
DELETE FROM credentials
WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, name, type, encrypted_data, description, created_at, updated_at
FROM credentials
WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EncryptedData,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByIDForUpdate = `-- name: GetCredentialByIDForUpdate :one
SELECT id, name, type, encrypted_data, description, created_at, updated_at
FROM credentials
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCredentialByIDForUpdate(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByIDForUpdate, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EncryptedData,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDiscoveryCollectorsWithConfig = `-- name: ListActiveDiscoveryCollectorsWithConfig :many
SELECT dsc.source_id, ds.name AS source_name, dsc.config_encrypted
FROM discovery_source_collectors dsc
JOIN discovery_sources ds ON ds.id = dsc.source_id
WHERE ds.deleted_at IS NULL AND dsc.config_encrypted IS NOT NULL
`

type ListActiveDiscoveryCollectorsWithConfigRow struct {
	SourceID        uuid.UUID   `json:"source_id"`
	SourceName      string      `json:"source_name"`
	ConfigEncrypted pgtype.Text `json:"config_encrypted"`
}

func (q *Queries) ListActiveDiscoveryCollectorsWithConfig(ctx context.Context) ([]ListActiveDiscoveryCollectorsWithConfigRow, error) {
	rows, err := q.db.Query(ctx, listActiveDiscoveryCollectorsWithConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDiscoveryCollectorsWithConfigRow{}
	for rows.Next() {
		var i ListActiveDiscoveryCollectorsWithConfigRow
		if err := rows.Scan(&i.SourceID, &i.SourceName, &i.ConfigEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDiscoverySourcesWithConfig = `-- name: ListActiveDiscoverySourcesWithConfig :many
SELECT id, name, config_encrypted
FROM discovery_sources
WHERE deleted_at IS NULL AND config_encrypted IS NOT NULL
`

type ListActiveDiscoverySourcesWithConfigRow struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	ConfigEncrypted pgtype.Text `json:"config_encrypted"`
}

func (q *Queries) ListActiveDiscoverySourcesWithConfig(ctx context.Context) ([]ListActiveDiscoverySourcesWithConfigRow, error) {
	rows, err := q.db.Query(ctx, listActiveDiscoverySourcesWithConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDiscoverySourcesWithConfigRow{}
	for rows.Next() {
		var i ListActiveDiscoverySourcesWithConfigRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ConfigEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, name, type, description, created_at, updated_at
FROM credentials
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListCredentialsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCredentialsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
