// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: discovery.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscoverySource = `-- name: CreateDiscoverySource :one
INSERT INTO discovery_sources (
    id, name, type, enabled, schedule_cron, config_encrypted, last_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, type, enabled, schedule_cron, config_encrypted, last_run_at, last_status, created_at, updated_at
`

type CreateDiscoverySourceParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Enabled         bool        `json:"enabled"`
	ScheduleCron    pgtype.Text `json:"schedule_cron"`
	ConfigEncrypted pgtype.Text `json:"config_encrypted"`
	LastStatus      string      `json:"last_status"`
}

func (q *Queries) CreateDiscoverySource(ctx context.Context, arg CreateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, createDiscoverySource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.ScheduleCron,
		arg.ConfigEncrypted,
		arg.LastStatus,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ScheduleCron,
		&i.ConfigEncrypted,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiscoverySource = `-- name: DeleteDiscoverySource :exec
DELETE FROM discovery_sources WHERE id = $1
`

func (q *Queries) DeleteDiscoverySource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscoverySource, id)
	return err
}

const getDiscoverySourceByID = `-- name: GetDiscoverySourceByID :one
SELECT id, name, type, enabled, schedule_cron, config_encrypted, last_run_at, last_status, created_at, updated_at FROM discovery_sources WHERE id = $1
`

func (q *Queries) GetDiscoverySourceByID(ctx context.Context, id uuid.UUID) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, getDiscoverySourceByID, id)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ScheduleCron,
		&i.ConfigEncrypted,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiscoveryRecordsByDevice = `-- name: ListDiscoveryRecordsByDevice :many
SELECT id, device_id, discovery_source_id, matched_by, raw_payload, last_scanned_at FROM device_discovery_records
WHERE device_id = $1
ORDER BY last_scanned_at DESC
`

func (q *Queries) ListDiscoveryRecordsByDevice(ctx context.Context, deviceID uuid.UUID) ([]DeviceDiscoveryRecord, error) {
	rows, err := q.db.Query(ctx, listDiscoveryRecordsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceDiscoveryRecord{}
	for rows.Next() {
		var i DeviceDiscoveryRecord
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.DiscoverySourceID,
			&i.MatchedBy,
			&i.RawPayload,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryRecordsBySource = `-- name: ListDiscoveryRecordsBySource :many
SELECT id, device_id, discovery_source_id, matched_by, raw_payload, last_scanned_at FROM device_discovery_records
WHERE discovery_source_id = $1
ORDER BY last_scanned_at DESC
LIMIT $2 OFFSET $3
`

type ListDiscoveryRecordsBySourceParams struct {
	DiscoverySourceID uuid.UUID `json:"discovery_source_id"`
	Limit             int32     `json:"limit"`
	Offset            int32     `json:"offset"`
}

func (q *Queries) ListDiscoveryRecordsBySource(ctx context.Context, arg ListDiscoveryRecordsBySourceParams) ([]DeviceDiscoveryRecord, error) {
	rows, err := q.db.Query(ctx, listDiscoveryRecordsBySource, arg.DiscoverySourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceDiscoveryRecord{}
	for rows.Next() {
		var i DeviceDiscoveryRecord
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.DiscoverySourceID,
			&i.MatchedBy,
			&i.RawPayload,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverySources = `-- name: ListDiscoverySources :many
SELECT id, name, type, enabled, schedule_cron, config_encrypted, last_run_at, last_status, created_at, updated_at FROM discovery_sources ORDER BY created_at DESC
`

func (q *Queries) ListDiscoverySources(ctx context.Context) ([]DiscoverySource, error) {
	rows, err := q.db.Query(ctx, listDiscoverySources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverySource{}
	for rows.Next() {
		var i DiscoverySource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.ScheduleCron,
			&i.ConfigEncrypted,
			&i.LastRunAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoverySourceStatus = `-- name: UpdateDiscoverySourceStatus :one
UPDATE discovery_sources
SET last_status = $2,
    last_run_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, enabled, schedule_cron, config_encrypted, last_run_at, last_status, created_at, updated_at
`

type UpdateDiscoverySourceStatusParams struct {
	ID         uuid.UUID `json:"id"`
	LastStatus string    `json:"last_status"`
}

func (q *Queries) UpdateDiscoverySourceStatus(ctx context.Context, arg UpdateDiscoverySourceStatusParams) (DiscoverySource, error) {
	row := q.db.QueryRow(ctx, updateDiscoverySourceStatus, arg.ID, arg.LastStatus)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ScheduleCron,
		&i.ConfigEncrypted,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDeviceDiscoveryRecord = `-- name: UpsertDeviceDiscoveryRecord :one
INSERT INTO device_discovery_records (
    id, device_id, discovery_source_id, matched_by, raw_payload, last_scanned_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (device_id, discovery_source_id) DO UPDATE
SET matched_by = EXCLUDED.matched_by,
    raw_payload = EXCLUDED.raw_payload,
    last_scanned_at = NOW()
RETURNING id, device_id, discovery_source_id, matched_by, raw_payload, last_scanned_at
`

type UpsertDeviceDiscoveryRecordParams struct {
	ID                uuid.UUID `json:"id"`
	DeviceID          uuid.UUID `json:"device_id"`
	DiscoverySourceID uuid.UUID `json:"discovery_source_id"`
	MatchedBy         string    `json:"matched_by"`
	RawPayload        []byte    `json:"raw_payload"`
}

func (q *Queries) UpsertDeviceDiscoveryRecord(ctx context.Context, arg UpsertDeviceDiscoveryRecordParams) (DeviceDiscoveryRecord, error) {
	row := q.db.QueryRow(ctx, upsertDeviceDiscoveryRecord,
		arg.ID,
		arg.DeviceID,
		arg.DiscoverySourceID,
		arg.MatchedBy,
		arg.RawPayload,
	)
	var i DeviceDiscoveryRecord
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DiscoverySourceID,
		&i.MatchedBy,
		&i.RawPayload,
		&i.LastScannedAt,
	)
	return i, err
}
