// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS alive
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var alive int32
	err := row.Scan(&alive)
	return alive, err
}
