// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory.sql

package db

import (
	"context"
	"net"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
WHERE (deleted_at IS NULL OR $1::boolean = true)
  AND ($2::text = '' OR hostname ILIKE '%' || $2 || '%' || $2 || '%')
  AND ($3::text = '' OR device_type = $3)
`

type CountDevicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountDevices(ctx context.Context, arg CountDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStagingDevices = `-- name: CountStagingDevices :one
SELECT COUNT(*) FROM device_staging WHERE status = $1
`

func (q *Queries) CountStagingDevices(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countStagingDevices, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, metadata, provider_scope, parent_provider_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count
`

type CreateDeviceParams struct {
	ID                uuid.UUID        `json:"id"`
	Hostname          string           `json:"hostname"`
	IpAddress         *netip.Addr      `json:"ip_address"`
	MacAddress        net.HardwareAddr `json:"mac_address"`
	Manufacturer      pgtype.Text      `json:"manufacturer"`
	Model             pgtype.Text      `json:"model"`
	SerialNumber      pgtype.Text      `json:"serial_number"`
	DeviceType        string           `json:"device_type"`
	Status            string           `json:"status"`
	Metadata          []byte           `json:"metadata"`
	ProviderScope     pgtype.Text      `json:"provider_scope"`
	ParentProviderRef pgtype.Text      `json:"parent_provider_ref"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceType,
		arg.Status,
		arg.Metadata,
		arg.ProviderScope,
		arg.ParentProviderRef,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const createStagingDevice = `-- name: CreateStagingDevice :one
INSERT INTO device_staging (
    id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at
`

type CreateStagingDeviceParams struct {
	ID                uuid.UUID        `json:"id"`
	Hostname          string           `json:"hostname"`
	IpAddress         *netip.Addr      `json:"ip_address"`
	MacAddress        net.HardwareAddr `json:"mac_address"`
	Manufacturer      pgtype.Text      `json:"manufacturer"`
	Model             pgtype.Text      `json:"model"`
	DeviceType        string           `json:"device_type"`
	DiscoverySourceID pgtype.UUID      `json:"discovery_source_id"`
	RawPayload        []byte           `json:"raw_payload"`
	Status            string           `json:"status"`
}

func (q *Queries) CreateStagingDevice(ctx context.Context, arg CreateStagingDeviceParams) (DeviceStaging, error) {
	row := q.db.QueryRow(ctx, createStagingDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.DeviceType,
		arg.DiscoverySourceID,
		arg.RawPayload,
		arg.Status,
	)
	var i DeviceStaging
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.DiscoverySourceID,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (
    id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at
`

type CreateSubnetParams struct {
	ID               uuid.UUID    `json:"id"`
	Name             string       `json:"name"`
	Cidr             netip.Prefix `json:"cidr"`
	VlanID           pgtype.Int4  `json:"vlan_id"`
	GatewayIp        *netip.Addr  `json:"gateway_ip"`
	Description      pgtype.Text  `json:"description"`
	DiscoveryEnabled bool         `json:"discovery_enabled"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, createSubnet,
		arg.ID,
		arg.Name,
		arg.Cidr,
		arg.VlanID,
		arg.GatewayIp,
		arg.Description,
		arg.DiscoveryEnabled,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.GatewayIp,
		&i.Description,
		&i.DiscoveryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count FROM devices
WHERE id = $1 AND (deleted_at IS NULL OR $2::boolean = true)
`

type GetDeviceByIDParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 bool      `json:"column_2"`
}

func (q *Queries) GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, arg.ID, arg.Column2)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const getDeviceByProviderRef = `-- name: GetDeviceByProviderRef :one
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count FROM devices
WHERE metadata->>'provider_ref' = $1::text AND deleted_at IS NULL
`

// Resolves a workload by its canonical identity, backed by the partial unique index
// uq_devices_provider_ref.
func (q *Queries) GetDeviceByProviderRef(ctx context.Context, providerRef string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByProviderRef, providerRef)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const getStagingDeviceByID = `-- name: GetStagingDeviceByID :one
SELECT id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at FROM device_staging WHERE id = $1
`

func (q *Queries) GetStagingDeviceByID(ctx context.Context, id uuid.UUID) (DeviceStaging, error) {
	row := q.db.QueryRow(ctx, getStagingDeviceByID, id)
	var i DeviceStaging
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.DiscoverySourceID,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at FROM subnets WHERE id = $1
`

func (q *Queries) GetSubnetByID(ctx context.Context, id uuid.UUID) (Subnet, error) {
	row := q.db.QueryRow(ctx, getSubnetByID, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.GatewayIp,
		&i.Description,
		&i.DiscoveryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count FROM devices
WHERE (deleted_at IS NULL OR $1::boolean = true)
  AND ($2::text = '' OR hostname ILIKE '%' || $2 || '%' || $2 || '%')
  AND ($3::text = '' OR device_type = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDevicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.DeviceType,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentProviderRef,
			&i.ParentDeviceID,
			&i.ProviderScope,
			&i.AbsenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByProviderScope = `-- name: ListDevicesByProviderScope :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count FROM devices
WHERE provider_scope = $1
  AND deleted_at IS NULL
  AND status <> 'archived'
`

// Every workload an authoritative provider owns in one scope. Archived devices are left
// out: they have already reached the end of the lifecycle and must not be counted again.
func (q *Queries) ListDevicesByProviderScope(ctx context.Context, providerScope pgtype.Text) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByProviderScope, providerScope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.DeviceType,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentProviderRef,
			&i.ParentDeviceID,
			&i.ProviderScope,
			&i.AbsenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesPendingParentResolution = `-- name: ListDevicesPendingParentResolution :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count FROM devices
WHERE parent_provider_ref = $1
  AND parent_device_id IS NULL
  AND deleted_at IS NULL
`

// Children that declared a parent the engine has not resolved to a device yet, which
// happens whenever a workload is discovered before its host. Backed by
// idx_devices_parent_provider_ref_pending.
func (q *Queries) ListDevicesPendingParentResolution(ctx context.Context, parentProviderRef pgtype.Text) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesPendingParentResolution, parentProviderRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.DeviceType,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentProviderRef,
			&i.ParentDeviceID,
			&i.ProviderScope,
			&i.AbsenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagingDevices = `-- name: ListStagingDevices :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at FROM device_staging
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStagingDevicesParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListStagingDevices(ctx context.Context, arg ListStagingDevicesParams) ([]DeviceStaging, error) {
	rows, err := q.db.Query(ctx, listStagingDevices, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceStaging{}
	for rows.Next() {
		var i DeviceStaging
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.DeviceType,
			&i.DiscoverySourceID,
			&i.RawPayload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at FROM subnets ORDER BY name ASC
`

func (q *Queries) ListSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.Query(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.VlanID,
			&i.GatewayIp,
			&i.Description,
			&i.DiscoveryEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceAbsent = `-- name: MarkDeviceAbsent :one
UPDATE devices
SET absence_count = absence_count + 1,
    status = CASE WHEN absence_count + 1 >= $2::int THEN 'archived' ELSE 'offline' END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count
`

type MarkDeviceAbsentParams struct {
	ID               uuid.UUID `json:"id"`
	ArchiveThreshold int32     `json:"archive_threshold"`
}

// Advances one device along the absence hysteresis: the first miss in an authoritative,
// complete run takes it offline, the second archives it. last_seen_at is deliberately left
// untouched so it keeps pointing at the last time the device was actually observed.
func (q *Queries) MarkDeviceAbsent(ctx context.Context, arg MarkDeviceAbsentParams) (Device, error) {
	row := q.db.QueryRow(ctx, markDeviceAbsent, arg.ID, arg.ArchiveThreshold)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const setDeviceParent = `-- name: SetDeviceParent :one
UPDATE devices
SET parent_device_id = $2,
    parent_provider_ref = COALESCE(NULLIF($3::text, ''), parent_provider_ref),
    updated_at = NOW()
WHERE id = $1
RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count
`

type SetDeviceParentParams struct {
	ID                uuid.UUID   `json:"id"`
	ParentDeviceID    pgtype.UUID `json:"parent_device_id"`
	ParentProviderRef string      `json:"parent_provider_ref"`
}

// Anchors a workload to its host. Kept apart from UpdateDevice so field reconciliation can
// never clobber the containment hierarchy, and vice versa.
func (q *Queries) SetDeviceParent(ctx context.Context, arg SetDeviceParentParams) (Device, error) {
	row := q.db.QueryRow(ctx, setDeviceParent, arg.ID, arg.ParentDeviceID, arg.ParentProviderRef)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
SET deleted_at = NOW(),
    status = 'deleted',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, id)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET hostname = $2,
    ip_address = $3,
    mac_address = $4,
    manufacturer = $5,
    model = $6,
    serial_number = $7,
    device_type = $8,
    status = $9,
    metadata = $10,
    provider_scope = COALESCE(NULLIF($11::text, ''), provider_scope),
    last_seen_at = NOW(),
    absence_count = 0,
    updated_at = NOW()
WHERE id = $1
RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at, parent_provider_ref, parent_device_id, provider_scope, absence_count
`

type UpdateDeviceParams struct {
	ID            uuid.UUID        `json:"id"`
	Hostname      string           `json:"hostname"`
	IpAddress     *netip.Addr      `json:"ip_address"`
	MacAddress    net.HardwareAddr `json:"mac_address"`
	Manufacturer  pgtype.Text      `json:"manufacturer"`
	Model         pgtype.Text      `json:"model"`
	SerialNumber  pgtype.Text      `json:"serial_number"`
	DeviceType    string           `json:"device_type"`
	Status        string           `json:"status"`
	Metadata      []byte           `json:"metadata"`
	ProviderScope string           `json:"provider_scope"`
}

// Observing a device is what proves it is still there, so every update refreshes
// last_seen_at and clears the absence streak that drives the lifecycle hysteresis.
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceType,
		arg.Status,
		arg.Metadata,
		arg.ProviderScope,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentProviderRef,
		&i.ParentDeviceID,
		&i.ProviderScope,
		&i.AbsenceCount,
	)
	return i, err
}

const updateStagingDeviceStatus = `-- name: UpdateStagingDeviceStatus :exec
UPDATE device_staging
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateStagingDeviceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateStagingDeviceStatus(ctx context.Context, arg UpdateStagingDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, updateStagingDeviceStatus, arg.ID, arg.Status)
	return err
}
