// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory.sql

package db

import (
	"context"
	"net"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
WHERE (deleted_at IS NULL OR $1::boolean = true)
  AND ($2::text = '' OR hostname ILIKE '%' || $2 || '%' || $2 || '%')
  AND ($3::text = '' OR device_type = $3)
`

type CountDevicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CountDevices(ctx context.Context, arg CountDevicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStagingDevices = `-- name: CountStagingDevices :one
SELECT COUNT(*) FROM device_staging WHERE status = $1
`

func (q *Queries) CountStagingDevices(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countStagingDevices, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at
`

type CreateDeviceParams struct {
	ID           uuid.UUID        `json:"id"`
	Hostname     string           `json:"hostname"`
	IpAddress    *netip.Addr      `json:"ip_address"`
	MacAddress   net.HardwareAddr `json:"mac_address"`
	Manufacturer pgtype.Text      `json:"manufacturer"`
	Model        pgtype.Text      `json:"model"`
	SerialNumber pgtype.Text      `json:"serial_number"`
	DeviceType   string           `json:"device_type"`
	Status       string           `json:"status"`
	Metadata     []byte           `json:"metadata"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceType,
		arg.Status,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStagingDevice = `-- name: CreateStagingDevice :one
INSERT INTO device_staging (
    id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at
`

type CreateStagingDeviceParams struct {
	ID                uuid.UUID        `json:"id"`
	Hostname          string           `json:"hostname"`
	IpAddress         *netip.Addr      `json:"ip_address"`
	MacAddress        net.HardwareAddr `json:"mac_address"`
	Manufacturer      pgtype.Text      `json:"manufacturer"`
	Model             pgtype.Text      `json:"model"`
	DeviceType        string           `json:"device_type"`
	DiscoverySourceID pgtype.UUID      `json:"discovery_source_id"`
	RawPayload        []byte           `json:"raw_payload"`
	Status            string           `json:"status"`
}

func (q *Queries) CreateStagingDevice(ctx context.Context, arg CreateStagingDeviceParams) (DeviceStaging, error) {
	row := q.db.QueryRow(ctx, createStagingDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.DeviceType,
		arg.DiscoverySourceID,
		arg.RawPayload,
		arg.Status,
	)
	var i DeviceStaging
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.DiscoverySourceID,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (
    id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at
`

type CreateSubnetParams struct {
	ID               uuid.UUID    `json:"id"`
	Name             string       `json:"name"`
	Cidr             netip.Prefix `json:"cidr"`
	VlanID           pgtype.Int4  `json:"vlan_id"`
	GatewayIp        *netip.Addr  `json:"gateway_ip"`
	Description      pgtype.Text  `json:"description"`
	DiscoveryEnabled bool         `json:"discovery_enabled"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, createSubnet,
		arg.ID,
		arg.Name,
		arg.Cidr,
		arg.VlanID,
		arg.GatewayIp,
		arg.Description,
		arg.DiscoveryEnabled,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.GatewayIp,
		&i.Description,
		&i.DiscoveryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at FROM devices
WHERE id = $1 AND (deleted_at IS NULL OR $2::boolean = true)
`

type GetDeviceByIDParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 bool      `json:"column_2"`
}

func (q *Queries) GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, arg.ID, arg.Column2)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStagingDeviceByID = `-- name: GetStagingDeviceByID :one
SELECT id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at FROM device_staging WHERE id = $1
`

func (q *Queries) GetStagingDeviceByID(ctx context.Context, id uuid.UUID) (DeviceStaging, error) {
	row := q.db.QueryRow(ctx, getStagingDeviceByID, id)
	var i DeviceStaging
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.DiscoverySourceID,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at FROM subnets WHERE id = $1
`

func (q *Queries) GetSubnetByID(ctx context.Context, id uuid.UUID) (Subnet, error) {
	row := q.db.QueryRow(ctx, getSubnetByID, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.GatewayIp,
		&i.Description,
		&i.DiscoveryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at FROM devices
WHERE (deleted_at IS NULL OR $1::boolean = true)
  AND ($2::text = '' OR hostname ILIKE '%' || $2 || '%' || $2 || '%')
  AND ($3::text = '' OR device_type = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDevicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNumber,
			&i.DeviceType,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagingDevices = `-- name: ListStagingDevices :many
SELECT id, hostname, ip_address, mac_address, manufacturer, model, device_type, discovery_source_id, raw_payload, status, created_at, updated_at FROM device_staging
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStagingDevicesParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListStagingDevices(ctx context.Context, arg ListStagingDevicesParams) ([]DeviceStaging, error) {
	rows, err := q.db.Query(ctx, listStagingDevices, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceStaging{}
	for rows.Next() {
		var i DeviceStaging
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.Manufacturer,
			&i.Model,
			&i.DeviceType,
			&i.DiscoverySourceID,
			&i.RawPayload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, name, cidr, vlan_id, gateway_ip, description, discovery_enabled, created_at, updated_at FROM subnets ORDER BY name ASC
`

func (q *Queries) ListSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.Query(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.VlanID,
			&i.GatewayIp,
			&i.Description,
			&i.DiscoveryEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
SET deleted_at = NOW(),
    status = 'deleted',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, id)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET hostname = $2,
    ip_address = $3,
    mac_address = $4,
    manufacturer = $5,
    model = $6,
    serial_number = $7,
    device_type = $8,
    status = $9,
    metadata = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, hostname, ip_address, mac_address, manufacturer, model, serial_number, device_type, status, first_seen_at, last_seen_at, metadata, deleted_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID           uuid.UUID        `json:"id"`
	Hostname     string           `json:"hostname"`
	IpAddress    *netip.Addr      `json:"ip_address"`
	MacAddress   net.HardwareAddr `json:"mac_address"`
	Manufacturer pgtype.Text      `json:"manufacturer"`
	Model        pgtype.Text      `json:"model"`
	SerialNumber pgtype.Text      `json:"serial_number"`
	DeviceType   string           `json:"device_type"`
	Status       string           `json:"status"`
	Metadata     []byte           `json:"metadata"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Hostname,
		arg.IpAddress,
		arg.MacAddress,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceType,
		arg.Status,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.IpAddress,
		&i.MacAddress,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceType,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStagingDeviceStatus = `-- name: UpdateStagingDeviceStatus :exec
UPDATE device_staging
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateStagingDeviceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateStagingDeviceStatus(ctx context.Context, arg UpdateStagingDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, updateStagingDeviceStatus, arg.ID, arg.Status)
	return err
}
