// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"net"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorName    string             `json:"actor_name"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Changes      []byte             `json:"changes"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID           uuid.UUID          `json:"id"`
	Hostname     string             `json:"hostname"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	MacAddress   net.HardwareAddr   `json:"mac_address"`
	Manufacturer pgtype.Text        `json:"manufacturer"`
	Model        pgtype.Text        `json:"model"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	DeviceType   string             `json:"device_type"`
	Status       string             `json:"status"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	Metadata     []byte             `json:"metadata"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeviceDiscoveryRecord struct {
	ID                uuid.UUID          `json:"id"`
	DeviceID          uuid.UUID          `json:"device_id"`
	DiscoverySourceID uuid.UUID          `json:"discovery_source_id"`
	MatchedBy         string             `json:"matched_by"`
	RawPayload        []byte             `json:"raw_payload"`
	LastScannedAt     pgtype.Timestamptz `json:"last_scanned_at"`
}

type DiscoverySource struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Enabled         bool               `json:"enabled"`
	ScheduleCron    pgtype.Text        `json:"schedule_cron"`
	ConfigEncrypted pgtype.Text        `json:"config_encrypted"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	LastStatus      string             `json:"last_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IpAddress struct {
	ID             uuid.UUID          `json:"id"`
	InterfaceID    pgtype.UUID        `json:"interface_id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	Address        netip.Addr         `json:"address"`
	Family         string             `json:"family"`
	AssignmentType string             `json:"assignment_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type NetworkInterface struct {
	ID         uuid.UUID          `json:"id"`
	DeviceID   uuid.UUID          `json:"device_id"`
	Name       string             `json:"name"`
	MacAddress net.HardwareAddr   `json:"mac_address"`
	VlanID     pgtype.Int4        `json:"vlan_id"`
	SpeedMbps  pgtype.Int4        `json:"speed_mbps"`
	IsVirtual  bool               `json:"is_virtual"`
	Status     string             `json:"status"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Resource    string             `json:"resource"`
	Action      string             `json:"action"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID          `json:"role_id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Subnet struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Cidr             netip.Prefix       `json:"cidr"`
	VlanID           pgtype.Int4        `json:"vlan_id"`
	GatewayIp        *netip.Addr        `json:"gateway_ip"`
	Description      pgtype.Text        `json:"description"`
	DiscoveryEnabled bool               `json:"discovery_enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SystemState struct {
	ID                    uuid.UUID          `json:"id"`
	OnboardingCompleted   bool               `json:"onboarding_completed"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	SystemInstanceID      uuid.UUID          `json:"system_instance_id"`
	TelemetryEnabled      bool               `json:"telemetry_enabled"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type TopologyLink struct {
	ID                uuid.UUID          `json:"id"`
	SourceDeviceID    uuid.UUID          `json:"source_device_id"`
	TargetDeviceID    uuid.UUID          `json:"target_device_id"`
	SourceInterfaceID pgtype.UUID        `json:"source_interface_id"`
	TargetInterfaceID pgtype.UUID        `json:"target_interface_id"`
	LinkType          string             `json:"link_type"`
	ConfidenceScore   pgtype.Numeric     `json:"confidence_score"`
	DiscoveredBy      string             `json:"discovered_by"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
