// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: topology.sql

package db

import (
	"context"
	"net"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTopologyLink = `-- name: CreateTopologyLink :one
INSERT INTO topology_links (
    id,
    source_device_id,
    target_device_id,
    source_interface_id,
    target_interface_id,
    link_type,
    confidence_score,
    discovered_by,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at
`

type CreateTopologyLinkParams struct {
	ID                uuid.UUID      `json:"id"`
	SourceDeviceID    uuid.UUID      `json:"source_device_id"`
	TargetDeviceID    uuid.UUID      `json:"target_device_id"`
	SourceInterfaceID pgtype.UUID    `json:"source_interface_id"`
	TargetInterfaceID pgtype.UUID    `json:"target_interface_id"`
	LinkType          string         `json:"link_type"`
	ConfidenceScore   pgtype.Numeric `json:"confidence_score"`
	DiscoveredBy      string         `json:"discovered_by"`
	Metadata          []byte         `json:"metadata"`
}

func (q *Queries) CreateTopologyLink(ctx context.Context, arg CreateTopologyLinkParams) (TopologyLink, error) {
	row := q.db.QueryRow(ctx, createTopologyLink,
		arg.ID,
		arg.SourceDeviceID,
		arg.TargetDeviceID,
		arg.SourceInterfaceID,
		arg.TargetInterfaceID,
		arg.LinkType,
		arg.ConfidenceScore,
		arg.DiscoveredBy,
		arg.Metadata,
	)
	var i TopologyLink
	err := row.Scan(
		&i.ID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.SourceInterfaceID,
		&i.TargetInterfaceID,
		&i.LinkType,
		&i.ConfidenceScore,
		&i.DiscoveredBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContainmentLinksForChild = `-- name: DeleteContainmentLinksForChild :execrows
DELETE FROM topology_links
WHERE target_device_id = $1
  AND link_type = $2
  AND source_device_id <> $3
`

type DeleteContainmentLinksForChildParams struct {
	TargetDeviceID uuid.UUID `json:"target_device_id"`
	LinkType       string    `json:"link_type"`
	SourceDeviceID uuid.UUID `json:"source_device_id"`
}

// Removes the containment edges anchoring a workload to a host. Used when a workload
// migrates: the old edge must disappear in the same transaction that creates the new one,
// or the graph would briefly show the workload living on two hosts at once.
func (q *Queries) DeleteContainmentLinksForChild(ctx context.Context, arg DeleteContainmentLinksForChildParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContainmentLinksForChild, arg.TargetDeviceID, arg.LinkType, arg.SourceDeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTopologyLink = `-- name: DeleteTopologyLink :execrows
DELETE FROM topology_links
WHERE id = $1
`

func (q *Queries) DeleteTopologyLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTopologyLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTopologyLinkByID = `-- name: GetTopologyLinkByID :one
SELECT id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at FROM topology_links
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTopologyLinkByID(ctx context.Context, id uuid.UUID) (TopologyLink, error) {
	row := q.db.QueryRow(ctx, getTopologyLinkByID, id)
	var i TopologyLink
	err := row.Scan(
		&i.ID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.SourceInterfaceID,
		&i.TargetInterfaceID,
		&i.LinkType,
		&i.ConfidenceScore,
		&i.DiscoveredBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDevicesForGraph = `-- name: ListActiveDevicesForGraph :many
SELECT 
    id,
    hostname,
    ip_address,
    mac_address,
    device_type,
    status,
    metadata
FROM devices
WHERE deleted_at IS NULL AND status != 'deleted'
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListActiveDevicesForGraphParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type ListActiveDevicesForGraphRow struct {
	ID         uuid.UUID        `json:"id"`
	Hostname   string           `json:"hostname"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	MacAddress net.HardwareAddr `json:"mac_address"`
	DeviceType string           `json:"device_type"`
	Status     string           `json:"status"`
	Metadata   []byte           `json:"metadata"`
}

func (q *Queries) ListActiveDevicesForGraph(ctx context.Context, arg ListActiveDevicesForGraphParams) ([]ListActiveDevicesForGraphRow, error) {
	rows, err := q.db.Query(ctx, listActiveDevicesForGraph, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDevicesForGraphRow{}
	for rows.Next() {
		var i ListActiveDevicesForGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.DeviceType,
			&i.Status,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTopologyLinksForGraph = `-- name: ListActiveTopologyLinksForGraph :many
SELECT 
    id,
    source_device_id,
    target_device_id,
    source_interface_id,
    target_interface_id,
    link_type,
    confidence_score,
    discovered_by,
    metadata
FROM topology_links
WHERE source_device_id IN (SELECT id FROM devices WHERE deleted_at IS NULL AND status != 'deleted')
  AND target_device_id IN (SELECT id FROM devices WHERE deleted_at IS NULL AND status != 'deleted')
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListActiveTopologyLinksForGraphParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type ListActiveTopologyLinksForGraphRow struct {
	ID                uuid.UUID      `json:"id"`
	SourceDeviceID    uuid.UUID      `json:"source_device_id"`
	TargetDeviceID    uuid.UUID      `json:"target_device_id"`
	SourceInterfaceID pgtype.UUID    `json:"source_interface_id"`
	TargetInterfaceID pgtype.UUID    `json:"target_interface_id"`
	LinkType          string         `json:"link_type"`
	ConfidenceScore   pgtype.Numeric `json:"confidence_score"`
	DiscoveredBy      string         `json:"discovered_by"`
	Metadata          []byte         `json:"metadata"`
}

func (q *Queries) ListActiveTopologyLinksForGraph(ctx context.Context, arg ListActiveTopologyLinksForGraphParams) ([]ListActiveTopologyLinksForGraphRow, error) {
	rows, err := q.db.Query(ctx, listActiveTopologyLinksForGraph, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTopologyLinksForGraphRow{}
	for rows.Next() {
		var i ListActiveTopologyLinksForGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.SourceInterfaceID,
			&i.TargetInterfaceID,
			&i.LinkType,
			&i.ConfidenceScore,
			&i.DiscoveredBy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyLinks = `-- name: ListTopologyLinks :many
SELECT id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at FROM topology_links
WHERE 
    ($1::varchar IS NULL OR link_type = $1)
    AND ($2::uuid IS NULL OR source_device_id = $2)
    AND ($3::uuid IS NULL OR target_device_id = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTopologyLinksParams struct {
	LinkType       pgtype.Text `json:"link_type"`
	SourceDeviceID pgtype.UUID `json:"source_device_id"`
	TargetDeviceID pgtype.UUID `json:"target_device_id"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListTopologyLinks(ctx context.Context, arg ListTopologyLinksParams) ([]TopologyLink, error) {
	rows, err := q.db.Query(ctx, listTopologyLinks,
		arg.LinkType,
		arg.SourceDeviceID,
		arg.TargetDeviceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopologyLink{}
	for rows.Next() {
		var i TopologyLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.SourceInterfaceID,
			&i.TargetInterfaceID,
			&i.LinkType,
			&i.ConfidenceScore,
			&i.DiscoveredBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContainmentLink = `-- name: UpsertContainmentLink :one
INSERT INTO topology_links (
    id, source_device_id, target_device_id, link_type, confidence_score, discovered_by, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (source_device_id, target_device_id, link_type)
DO UPDATE SET metadata = EXCLUDED.metadata,
              confidence_score = EXCLUDED.confidence_score,
              discovered_by = EXCLUDED.discovered_by,
              updated_at = CURRENT_TIMESTAMP
RETURNING id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at
`

type UpsertContainmentLinkParams struct {
	ID              uuid.UUID      `json:"id"`
	SourceDeviceID  uuid.UUID      `json:"source_device_id"`
	TargetDeviceID  uuid.UUID      `json:"target_device_id"`
	LinkType        string         `json:"link_type"`
	ConfidenceScore pgtype.Numeric `json:"confidence_score"`
	DiscoveredBy    string         `json:"discovered_by"`
	Metadata        []byte         `json:"metadata"`
}

// Idempotent containment edge. Repeated discovery runs re-report the same parentage, and
// uq_topology_links_source_target_type turns the retry into a no-op update.
func (q *Queries) UpsertContainmentLink(ctx context.Context, arg UpsertContainmentLinkParams) (TopologyLink, error) {
	row := q.db.QueryRow(ctx, upsertContainmentLink,
		arg.ID,
		arg.SourceDeviceID,
		arg.TargetDeviceID,
		arg.LinkType,
		arg.ConfidenceScore,
		arg.DiscoveredBy,
		arg.Metadata,
	)
	var i TopologyLink
	err := row.Scan(
		&i.ID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.SourceInterfaceID,
		&i.TargetInterfaceID,
		&i.LinkType,
		&i.ConfidenceScore,
		&i.DiscoveredBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
