// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: topology.sql

package db

import (
	"context"
	"net"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTopologyLink = `-- name: CreateTopologyLink :one
INSERT INTO topology_links (
    id,
    source_device_id,
    target_device_id,
    source_interface_id,
    target_interface_id,
    link_type,
    confidence_score,
    discovered_by,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at
`

type CreateTopologyLinkParams struct {
	ID                uuid.UUID      `json:"id"`
	SourceDeviceID    uuid.UUID      `json:"source_device_id"`
	TargetDeviceID    uuid.UUID      `json:"target_device_id"`
	SourceInterfaceID pgtype.UUID    `json:"source_interface_id"`
	TargetInterfaceID pgtype.UUID    `json:"target_interface_id"`
	LinkType          string         `json:"link_type"`
	ConfidenceScore   pgtype.Numeric `json:"confidence_score"`
	DiscoveredBy      string         `json:"discovered_by"`
	Metadata          []byte         `json:"metadata"`
}

func (q *Queries) CreateTopologyLink(ctx context.Context, arg CreateTopologyLinkParams) (TopologyLink, error) {
	row := q.db.QueryRow(ctx, createTopologyLink,
		arg.ID,
		arg.SourceDeviceID,
		arg.TargetDeviceID,
		arg.SourceInterfaceID,
		arg.TargetInterfaceID,
		arg.LinkType,
		arg.ConfidenceScore,
		arg.DiscoveredBy,
		arg.Metadata,
	)
	var i TopologyLink
	err := row.Scan(
		&i.ID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.SourceInterfaceID,
		&i.TargetInterfaceID,
		&i.LinkType,
		&i.ConfidenceScore,
		&i.DiscoveredBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTopologyLink = `-- name: DeleteTopologyLink :exec
DELETE FROM topology_links
WHERE id = $1
`

func (q *Queries) DeleteTopologyLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopologyLink, id)
	return err
}

const getTopologyLinkByID = `-- name: GetTopologyLinkByID :one
SELECT id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at FROM topology_links
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTopologyLinkByID(ctx context.Context, id uuid.UUID) (TopologyLink, error) {
	row := q.db.QueryRow(ctx, getTopologyLinkByID, id)
	var i TopologyLink
	err := row.Scan(
		&i.ID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.SourceInterfaceID,
		&i.TargetInterfaceID,
		&i.LinkType,
		&i.ConfidenceScore,
		&i.DiscoveredBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllActiveNodesAndLinks = `-- name: ListAllActiveNodesAndLinks :many
SELECT 
    d.id AS device_id,
    d.hostname,
    d.ip_address,
    d.mac_address,
    d.device_type,
    d.status,
    d.metadata AS device_metadata,
    tl.id AS link_id,
    tl.source_device_id,
    tl.target_device_id,
    tl.source_interface_id,
    tl.target_interface_id,
    tl.link_type,
    tl.confidence_score,
    tl.discovered_by,
    tl.metadata AS link_metadata
FROM devices d
LEFT JOIN topology_links tl ON (d.id = tl.source_device_id OR d.id = tl.target_device_id)
WHERE d.status != 'deleted'
`

type ListAllActiveNodesAndLinksRow struct {
	DeviceID          uuid.UUID        `json:"device_id"`
	Hostname          string           `json:"hostname"`
	IpAddress         *netip.Addr      `json:"ip_address"`
	MacAddress        net.HardwareAddr `json:"mac_address"`
	DeviceType        string           `json:"device_type"`
	Status            string           `json:"status"`
	DeviceMetadata    []byte           `json:"device_metadata"`
	LinkID            pgtype.UUID      `json:"link_id"`
	SourceDeviceID    pgtype.UUID      `json:"source_device_id"`
	TargetDeviceID    pgtype.UUID      `json:"target_device_id"`
	SourceInterfaceID pgtype.UUID      `json:"source_interface_id"`
	TargetInterfaceID pgtype.UUID      `json:"target_interface_id"`
	LinkType          pgtype.Text      `json:"link_type"`
	ConfidenceScore   pgtype.Numeric   `json:"confidence_score"`
	DiscoveredBy      pgtype.Text      `json:"discovered_by"`
	LinkMetadata      []byte           `json:"link_metadata"`
}

func (q *Queries) ListAllActiveNodesAndLinks(ctx context.Context) ([]ListAllActiveNodesAndLinksRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveNodesAndLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveNodesAndLinksRow{}
	for rows.Next() {
		var i ListAllActiveNodesAndLinksRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Hostname,
			&i.IpAddress,
			&i.MacAddress,
			&i.DeviceType,
			&i.Status,
			&i.DeviceMetadata,
			&i.LinkID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.SourceInterfaceID,
			&i.TargetInterfaceID,
			&i.LinkType,
			&i.ConfidenceScore,
			&i.DiscoveredBy,
			&i.LinkMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyLinks = `-- name: ListTopologyLinks :many
SELECT id, source_device_id, target_device_id, source_interface_id, target_interface_id, link_type, confidence_score, discovered_by, metadata, created_at, updated_at FROM topology_links
WHERE 
    ($1::varchar IS NULL OR link_type = $1)
    AND ($2::uuid IS NULL OR source_device_id = $2)
    AND ($3::uuid IS NULL OR target_device_id = $3)
ORDER BY created_at DESC
`

type ListTopologyLinksParams struct {
	LinkType       pgtype.Text `json:"link_type"`
	SourceDeviceID pgtype.UUID `json:"source_device_id"`
	TargetDeviceID pgtype.UUID `json:"target_device_id"`
}

func (q *Queries) ListTopologyLinks(ctx context.Context, arg ListTopologyLinksParams) ([]TopologyLink, error) {
	rows, err := q.db.Query(ctx, listTopologyLinks, arg.LinkType, arg.SourceDeviceID, arg.TargetDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopologyLink{}
	for rows.Next() {
		var i TopologyLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.SourceInterfaceID,
			&i.TargetInterfaceID,
			&i.LinkType,
			&i.ConfidenceScore,
			&i.DiscoveredBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
